
---------------INSERT() QUERY-----------------
SELECT NVL(MAX(TO_NUMBER(CODE)),0) FROM NOTICE
--GET LIST
SELECT * 
FROM(
	SELECT ROWNUM NUM, N.* 
	FROM(
		SELECT *
		FROM
			NOTICE VIEW
		WHERE TITLE LIKE '%%'
		ORDER BY REGDATE DESC
	)N
)
WHERE NUM BETWEEN 11 AND 20

SELECT MAX(TO_NUMBER(CODE)) FROM NOTICE

SELECT *  FROM NOTICE

DELETE NOTICE WHERE CODE=1106

